### ISSUE TITLE
logcollector breaks with duplicate localfile entries

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#2421]
## Bug report

**OS**: CentOS7
**Wazuh version**: 3.7.2
**Install type**: manager

## Details

```xml
  <global>
    ....
    <logall_json>yes</logall_json>
  </global>
...
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>
```
By mistake I had the configuration above. Two duplicate entries for `/var/log/maillog`. The I get the following warning in `ossec.log`:

```
2019/01/21 18:59:34 ossec-logcollector: WARNING: (1958): Log file '/var/log/maillog' is duplicated.
```
In this situation logcollectors breaks somehow. The files being monitored are no longer processed. Any of the files monitored via `localfile`. For example, `/var/log/messages`. Nothing shows in `archives.json`.

**Comment by Cerv1** [comment]
Hello @rossengeorgiev,

You are right, this is a known bug in *Wazuh 3.7.2* and it's caused, as you said, by a duplicated `<localfile>`. 

This is the issue related to this bug (#2161) and it has been fixed in the last version of *Wazuh 3.7.2*. You can update your `wazuh-manager` to the latest version of *Wazuh 3.7.2 (revision: 3727)* or the recenlty released *Wazuh 3.8.0* in order to get the changes.

Best regards,
Cerv1.

**Comment by rossengeorgiev** [comment]
Hi @Cerv1 are you sure its fixed? Just checked my revision:

```bash
# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.7.2"
REVISION="3727"
DATE="Thu Dec 13 20:20:11 UTC 2018"
TYPE="server"
```

**Comment by Cerv1** [comment]
Hi @rossengeorgiev,

I've just tested your example. Please see the output below:

```
# cat /etc/ossec-init.conf 
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.7.2"
REVISION="3727"
DATE="Thu Dec 13 20:20:11 UTC 2018"
TYPE="server"

# echo "Testing logcollector... 1... 2... 3..." >> /var/log/messages 

# tail /var/ossec/logs/archives/archives.json
... 
{"timestamp":"2019-01-22T12:29:57.924+0000","agent":{"id":"000","name":"ManagerCentOS7"},"manager":{"name":"ManagerCentOS7"},"id":"1548160197.45388","full_log":"Testing logcollector... 1... 2... 3...","decoder":{},"location":"/var/log/messages"}
...

# tail /var/ossec/logs/archives/archives.log
...
2019 Jan 22 12:29:57 ManagerCentOS7->/var/log/messages Testing logcollector... 1... 2... 3...
...
```

As you can see, I'm getting the data and my configuration has the same duplicated localfile that you have. 

Please, can you verify that the `<logall>` and `<logall_json>` labels contains the correct value *(yes)*?

Furthermore, could you please give me the output of the following command?

```
# systemctl status wazuh-manager
```

Best regards,
Cerv1.

**Comment by rossengeorgiev** [comment]
Yep, I am still seeing the issue. See log below. This host Wazuh 2.1 and upgraded to 3.7.2. Not sure if that is important.
```bash
# grep logall /var/ossec/etc/ossec.conf
    <logall>yes</logall>
    <logall_json>yes</logall_json>
# grep -A 1 -B 2 maillog /var/ossec/etc/ossec.conf
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>
--
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>
# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.7.2"
REVISION="3727"
DATE="Thu Dec 13 20:20:11 UTC 2018"
TYPE="server"
# systemctl restart wazuh-manager
# grep duplicate /var/ossec/logs/ossec.log
2019/01/22 13:56:22 ossec-logcollector: WARNING: (1958): Log file '/var/log/maillog' is duplicated.
# echo "Testing logcollector... 1... 2... 3..." >> /var/log/messages
# grep Testing /var/ossec/logs/archives/archives.json
# grep Testing /var/ossec/logs/archives/archives.log
# tail -1 /var/ossec/logs/archives/archives.log
2019 Jan 22 13:56:59 (monitor.local) any->/var/log/audit/audit.log type=SYSCALL....
# tail -1 /var/ossec/logs/archives/archives.json
{"timestamp":"2019-01-22T13:56:59.895+0000","rule":{"le.....

```

**Comment by Cerv1** [comment]
Hi @rossengeorgiev,

Could you please give me the output of the following command?
```
# systemctl status wazuh-manager
```
Now, let's set `ossec-logcollector` in debug mode and see if we have some useful information. To do this, just follow the steps below:

1. `# echo "logcollector.debug=2" >> /var/ossec/etc/local_internal_options.conf `
 
2. `# systemctl restart wazuh-manager`

3. Write something into any localfile monitored (e.g., ` /var/log/messages`)

Now, paste here the output of your `ossec.log` with the following command:

```
# cat /var/ossec/logs/ossec.log | grep ossec-logcollector
```

Best regards,
Cerv1.

**Comment by rossengeorgiev** [comment]
`/var/log/messages`
```
2019-01-24T17:00:56.703164+00:00 lognode-01.local kernel: ossec-logcollec[7557]: segfault at 0 ip           (null) sp 00007f5228c09e88 error 14 in ossec-logcollector[400000+89000]
```
`cat /var/ossec/logs/ossec.log | grep ossec-logcollector`
```
2019/01/24 17:00:53 ossec-logcollector[7494] debug_op.c:251 at os_logging_config(): DEBUG: (1228): Element 'log_format' without any option.
2019/01/24 17:00:53 ossec-logcollector[7494] main.c:178 at main(): DEBUG: Starting ...
2019/01/24 17:00:54 ossec-logcollector[7494] mq_op.c:46 at StartMQ(): DEBUG: (unix_domain) Maximum send buffer set to: '212992'.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:111 at LogCollectorStart(): DEBUG: Entering LogCollectorStart().
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:846 at set_read(): INFO: (1950): Analyzing file: '/var/log/audit/audit.log'.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:865 at set_read(): DEBUG: Socket target for '/var/log/audit/audit.log' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:846 at set_read(): INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:865 at set_read(): DEBUG: Socket target for '/var/ossec/logs/active-responses.log' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:846 at set_read(): INFO: (1950): Analyzing file: '/var/log/messages'.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:865 at set_read(): DEBUG: Socket target for '/var/log/messages' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:846 at set_read(): INFO: (1950): Analyzing file: '/var/log/secure'.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:865 at set_read(): DEBUG: Socket target for '/var/log/secure' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:991 at remove_duplicates(): WARNING: (1958): Log file '/var/log/maillog' is duplicated.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:1001 at remove_duplicates(): DEBUG: (1961): Files being monitored: 5/1000.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:187 at LogCollectorStart(): INFO: Monitoring full output of command(360): last -n 20
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:191 at LogCollectorStart(): DEBUG: Socket target for 'last -n 20' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:846 at set_read(): INFO: (1950): Analyzing file: '/var/log/maillog'.
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:865 at set_read(): DEBUG: Socket target for '/var/log/maillog' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:165 at LogCollectorStart(): INFO: Monitoring output of command(360): df -P
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:169 at LogCollectorStart(): DEBUG: Socket target for 'df -P' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:187 at LogCollectorStart(): INFO: Monitoring full output of command(360): netstat -tln | grep -v 127.0.0.1 | sort
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:191 at LogCollectorStart(): DEBUG: Socket target for 'netstat -tln | grep -v 127.0.0.1 | sort' -> agent
2019/01/24 17:00:54 ossec-logcollector[7494] pthreads_op.c:44 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/01/24 17:00:54 ossec-logcollector[7494] pthreads_op.c:44 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/01/24 17:00:54 ossec-logcollector[7494] pthreads_op.c:44 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/01/24 17:00:54 ossec-logcollector[7494] pthreads_op.c:44 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/01/24 17:00:54 ossec-logcollector[7494] pthreads_op.c:44 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:235 at LogCollectorStart(): INFO: Started (pid: 7494).
2019/01/24 17:00:54 ossec-logcollector[7494] logcollector.c:236 at LogCollectorStart(): DEBUG: (1961): Files being monitored: 5/1000.
2019/01/24 17:00:54 ossec-logcollector[7494] pthreads_op.c:44 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2019/01/24 17:00:54 ossec-logcollector[7494] lccom.c:100 at lccom_main(): DEBUG: Local requests thread ready
2019/01/24 17:00:56 ossec-logcollector[7494] read_audit.c:120 at read_audit(): DEBUG: Read 4 lines from /var/log/audit/audit.log
2019/01/24 17:00:56 ossec-logcollector[7494] read_syslog.c:85 at read_syslog(): DEBUG: Reading syslog message: '2019-01-24T17:00:55.749511+00:00 lognode-01.local wazuh-manager:'...
2019/01/24 17:00:56 ossec-logcollector[7494] read_syslog.c:85 at read_syslog(): DEBUG: Reading syslog message: '2019-01-24T17:00:55.750067+00:00 lognode-01.local systemd: Start'...
2019/01/24 17:00:56 ossec-logcollector[7494] read_syslog.c:117 at read_syslog(): DEBUG: Read 2 lines from /var/log/messages
2019/01/24 17:00:56 ossec-logcollector[7494] read_syslog.c:85 at read_syslog(): DEBUG: Reading syslog message: '2019-01-24T17:00:55.757385+00:00 lognode-01.local polkitd[692]: '...
2019/01/24 17:00:56 ossec-logcollector[7494] read_syslog.c:117 at read_syslog(): DEBUG: Read 1 lines from /var/log/secure
2019/01/24 17:00:56 ossec-logcollector[7494] read_fullcommand.c:27 at read_fullcommand(): DEBUG: Running full command 'last -n 20'
2019/01/24 17:00:56 ossec-logcollector[7494] read_command.c:25 at read_command(): DEBUG: Running command 'df -P'
2019/01/24 17:00:56 ossec-logcollector[7494] read_fullcommand.c:27 at read_fullcommand(): DEBUG: Running full command 'netstat -tln | grep -v 127.0.0.1 | sort'
```

**Comment by vikman90** [comment]
Hi @rossengeorgiev,

We think that this issue is related to #2161. If we are right, it was already fixed (#2154) for version 3.8.0, not 3.7.2 —in fact, this bug appeared in 3.7.2—. 

We merged that PR into branch 3.7 after the 3.7.2 release, and then we merged that branch into 3.8. Sorry for the confusion.

We've just release 3.8.1. Can you give it a try? We hope it resolves the problem.

Thanks for your feedback.
Best regards.

**Comment by rossengeorgiev** [comment]
hi @vikman90, seems to work on `3.8.2`. Files being monitored in DEBUG output shows -1.

```
2019/02/01 13:57:22 ossec-logcollector[2251] logcollector.c:1026 at remove_duplicates(): WARNING: (1958): Log file '/var/log/maillog' is duplicated.
2019/02/01 13:57:22 ossec-logcollector[2251] logcollector.c:1036 at remove_duplicates(): DEBUG: (1961): Files being monitored: -1/1000.
```
