### ISSUE TITLE
Manager - Status: Wazuh API returned an error message. Error: Error getting configuration.

### ISSUE THREAD

**Issue by hafeezy2j** [wazuh/wazuh#280]
Hello, I'm getting above mentioned error when I access MANAGER Tab under Wazuh app on Kibana.

tail -f /var/ossec/logs/api.log

WazuhAPI 2017-11-16 15:54:31: [::ffff:172.XX.13.69] GET /agents/?offset=0&limit=1&sort=-id - 200 - error: '0'.
WazuhAPI 2017-11-16 15:54:31: [::ffff:172.XX.13.69] GET /rules/?offset=0&limit=1 - 200 - error: '1101'.
WazuhAPI 2017-11-16 15:54:31: [::ffff:172.XX.13.69] GET /agents/074? - 200 - error: '0'.
WazuhAPI 2017-11-16 15:55:08: [::ffff:172.XX.13.69] GET /manager/logs? - 200 - error: '0'.
WazuhAPI 2017-11-16 15:55:09: [::ffff:172.XX.13.69] GET /manager/logs?offset=0&limit=250 - 200 - error: '0'.
WazuhAPI 2017-11-16 15:55:09: [::ffff:172.XX.13.69] GET /manager/logs/summary? - 200 - error: '0'.
WazuhAPI 2017-11-16 15:55:09: [::ffff:172.XX.13.69] GET /manager/logs?category=all&type_log=all&offset=0&limit=250 - 200 - error: '0'.
WazuhAPI 2017-11-16 16:00:01: [::ffff:172.XX.13.69] GET /agents/?offset=0&limit=1 - 200 - error: '0'.
WazuhAPI 2017-11-16 16:00:01: [::ffff:172.XX.13.69] GET /agents/?offset=0&limit=72 - 200 - error: '0'.

Here's what I have:

Centos 7 64-bit
Wazuh v2.1.1 
wazuh-api-2.1.1
logstash 5.6.2
elasticsearch  Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z, JVM: 1.8.0_144
kibana 5.6.4

 cd /var/ossec/var/db/
 sqlite3 global.db
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from info;
max_agents|8000
openssl_support|yes

here are the screenshot of the errors:

![image](https://user-images.githubusercontent.com/31100825/32916197-52d2cd06-cae9-11e7-87e9-2125fd598c2a.png)

![screenshot1](https://user-images.githubusercontent.com/31100825/32916397-f54ce4ae-cae9-11e7-9bee-eb964ba18644.png)

![screenshot2](https://user-images.githubusercontent.com/31100825/32916398-f562e6a0-cae9-11e7-8660-9267be3740a6.png)

**Comment by mgmacias95** [comment]
Hello @hafeezy2j,

This is a known bug in the XML parser used by the API. This bug happens when a comment with two or more `-` are read on the XML file. 

For example, adding this line to my `ossec.conf` gave me the same error as you:
```
<!-- --- -->
```

This bug is fixed on the new incoming Wazuh 3.0 release, but if you want to fix that for Wazuh 2.1 just remove the comment with the `-`. To find it out:
```shellsession
# cat /var/ossec/etc/ossec.conf | grep -e "--"
<!--
-->
  <!-- Choose between plain or json format (or both) for internal logs -->
  <!-- Policy monitoring -->
    <!-- Frequency that rootcheck is executed - every 12 hours -->
  <!-- File integrity monitoring -->
    <!-- Frequency that syscheck is executed default every 12 hours -->
    <!-- Generate alert when new file detected -->
    <!-- Don't ignore files that change more than 3 times -->
    <!-- Directories to check  (perform all possible verifications) -->
    <!-- Files/directories to ignore -->
    <!-- Check the file, but never compute the diff -->
<!-- --- -->
  <!-- Active - response -->
  <!--
  -->
  <!-- Log analysis -->
    <!-- Default ruleset -->
    <!-- User-defined ruleset -->
  <!-- Configuration for ossec-authd
  -->
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
# cat /var/ossec/etc/ossec.conf | grep -e "---"
<!-- --- -->
```

Please tell us if this solution worked for you.

Best regards,
Marta

**Comment by hafeezy2j** [comment]
Hello @mgmacias95 ,

I have removed all comments which includes "--" or "---" from my  ossec.conf on wazuh server but I'm still getting errors.  

cat /var/ossec/etc/ossec.conf | grep -e "--"
cat /var/ossec/etc/ossec.conf | grep -e "---"

Any other clues? I dont wish to upgrade to Wazuh 3.0 as its still in beta.

Thanks,
Hafeez

**Comment by mgmacias95** [comment]
Hello @hafeezy2j,

This is the piece of code that is failing:

https://github.com/wazuh/wazuh/blob/7202ac9c6c131763d92d3febc8b5a7da353de2dd/framework/wazuh/configuration.py#L361-L375

As you can see, the exception is raised without a good error description. I'm going to describe how to change that in the code and run it again. This way, we'll know exactly what is happening.

1. Edit the file `/var/ossec/api/framework/wazuh/configuration.py` and change lines 375 and 374 for these ones (since python is interpreted, there's no need to recompile or reinstall again):
```python
except Exception as e: 
    raise WazuhException(1101, str(e))
```
2. Run the following API call:
```shellsession
$ curl -u foo:bar "localhost:55000/manager/configuration?pretty"
{
   "error": 1101,
   "message": "Error getting configuration: not well-formed (invalid token): line 19, column 7"
}
```

And paste the error message here 😄 

Best regards,
Marta

**Comment by hafeezy2j** [comment]
Hello,

Here's what I'm getting now

curl -u foo:bar "localhost:55000/manager/configuration?pretty"
curl: (52) Empty reply from server

![image](https://user-images.githubusercontent.com/31100825/32954441-1bd37768-cb81-11e7-9a76-6db98a1910da.png)

![image](https://user-images.githubusercontent.com/31100825/32954574-816d68fe-cb81-11e7-8303-84f399782a6c.png)

![image](https://user-images.githubusercontent.com/31100825/32954605-95402e2a-cb81-11e7-8aa9-ce715e06be86.png)

Thanks,
Hafeez

**Comment by mgmacias95** [comment]
Hello @hafeezy2j,

The `raise` line must have 4 spaces to work properly. This is the error that is showing you:

```python
except Exception as e:
_ _ _ _ raise...
```

Sorry for the inconvenience,
Marta

**Comment by hafeezy2j** [comment]
Hello @mgmacias95 ,

I'm getting now..

![image](https://user-images.githubusercontent.com/31100825/32955895-489db3ae-cb85-11e7-9aca-aef6108c7daa.png)

curl -u foo:bar "localhost:55000/manager/configuration?pretty"
curl: (52) Empty reply from server

![image](https://user-images.githubusercontent.com/31100825/32955829-177983a2-cb85-11e7-9406-aeb97675f12c.png)

Thanks,
Hafeez

**Comment by mgmacias95** [comment]
Hello @hafeezy2j,

Fist of all, I think the "empty reply from server" response the API is giving to you is caused because the API is configured with https. 

The Kibana screenshot you posted shows the error seems to be on the line 262 of your ossec.conf.  Please, delete that line and try again. If that doesn't work, paste that line here so I can help you.

Best regards,
Marta

**Comment by hafeezy2j** [comment]
hello @mgmacias95,

I have corrected that line and everything back up and running now. Do you think I should revert back the changes which I have made to /var/ossec/api/framework/wazuh/configuration.py or leave them as it is?

Thanks,
hafeez

**Comment by mgmacias95** [comment]
Hello @hafeezy2j,

The changes you've made don't affect to API / Kibana so you can leave it like this without any problem.

Best regards,
Marta

**Comment by hafeezy2j** [comment]
Hello @mgmacias95 
I was having trouble upgrading my previous elasticstack so I decided to prepare a new one. For some reason when I try to add wazuh-api in my wazhu app, I'm getting different errors. I have tried both https and http and I'm getting "Settings. Could not connect with Wazuh API, please check url and port and try again" error..

From command prompt of elastic stack, everything works fine:
curl -u wazuhapi**r:**** -k http://172.XX.XX.68:55000?pretty
{
   "error": 0,
   "data": "Welcome to Wazuh HIDS API"
}

Thanks,
Hafeez

**Comment by JuanjiJG** [comment]
Hi @hafeezy2j,

What is your current version of the Elastic Stack? If you're using Elastic 6, keep in mind that **only Wazuh 3.x is compatible** with that version.

According to the output of your call to the API, you're using **Wazuh 2.x**. The current output for Wazuh 3.x should be something like this:
```
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.1.0",
      "hostname": "ubuntu",
      "timestamp": "Tue Feb 06 2018 09:00:19 GMT+0100 (CET)"
   }
}
```

I recommend you to upgrade to Wazuh 3.1, our latest version, and also to Elastic 6.1.3. You can follow our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html#upgrading-different-major) in order to achieve this without errors.

Let us know if you're still having problems or doubts with the upgrading process.

Best regards,
Juanjo
