### ISSUE TITLE
Cross-Cluster Search (CCS) Alert Problem

### ISSUE THREAD

**Issue by SkullKid16** [wazuh/wazuh#29352]
Hello, I hope someone can help me with this problem. I followed these instructions at https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/, except that I installed the server and indexer on the same machine for each cluster. However, I'm now getting the error shown in the screenshot.

![Image](https://github.com/user-attachments/assets/f6b2e09b-1ad5-4b26-bedc-8f4e90761a31)

**Comment by SkullKid16** [comment]
I figured out that I'm calling the indexer using the public IP, which is the firewall's IP. I've opened all the necessary ports using NAT. However, I get the private IP back. I entered the private IP in the opensearch.yml. My goal is actually for the server and indexer to have the same IP in the cluster, so that both run on the same machine. What's the best way to do this if the clusters are behind a firewall?

![Image](https://github.com/user-attachments/assets/c858b99c-52db-40ef-8270-8069354d6339)

**Comment by MiguelazoDS** [comment]
Hi, sorry for the delay. Do you open incoming connections in your wazuh-indexer on 9300? 

What do you get with this command 

`curl -k -u <user:pass> https://indexer-ip:9300/_cluster/health`

**Comment by SkullKid16** [comment]
Thanks for your help, everything's working now except that if a cluster fails, the dashboard takes forever to load. For example, if cluster A fails and I switch to cluster B, the dashboard takes forever to load. As you can see in the screenshot.

![Image](https://github.com/user-attachments/assets/8b157049-ef28-4451-bb15-e36567875dae)

**Comment by MiguelazoDS** [comment]
Does it eventually work again?

**Comment by SkullKid16** [comment]
yes if all clusters are online everything works.

**Comment by MiguelazoDS** [comment]
I would say that this may be expected in a CCS environment, the Opensearch dashboard has to switch between indexers and perform request operation to retrieve the data, in a master-worker architecture the Opensearch dashboard communicates only with the master node.  

Is there anything else that you consider is not working properly with this setup?

**Comment by SkullKid16** [comment]
How else can this be implemented so that clusters can fail and the main node still displays the results of the clusters that are online?

**Comment by SkullKid16** [comment]
Thats the problem statement from the blog post:

"A cybersecurity operations company that provides managed Security Operations Center (SOC) service to customers wants to use the Wazuh SIEM and XDR. The company has two new customers, organizations A and B, who wish to subscribe to their managed SOC service."

What happens if a customer's network goes down? Then nothing will work anymore.

**Comment by MiguelazoDS** [comment]
> I don't know if my problem has been understood correctly. If a customer's network fails, for example, Cluster A, then I can no longer access information about Cluster B on the main node.

Yeap, my bad, I understood that eventually (waiting some time) the environment worked as expected for your B cluster once the A goes down.

Let me keep taking a look at this and discuss this with the team in charge.

**Comment by MiguelazoDS** [comment]
I'll try to replicate this, we agreed with the dashboard team that is not expected. 

- So do you have 3 machines involved in this setup? one for cluster A, another for cluster B, and the last one for CCS environment? 
- What OS are the machines running?

**Comment by SkullKid16** [comment]
Thank you very much for following up on this. Exactly, like in the blog post, I have three systems.

The CCS environment consists of an Ubuntu Server 24.04, on which I have installed the dashboard, indexer, and server.

Cluster A runs on Ubuntu Server 22.04, and the dashboard, indexer, and server are also installed. The same applies to Cluster B.

**Comment by MiguelazoDS** [comment]
Thanks for the information, I'm analyzing the case now. 

Just to clarify, in the blog the CSS environment does not have a Wazuh server connected, it is just Wazuh Indexer and Wazuh Dashboard. 

And for the clusters, it only consists of Wazuh Server and Wazuh Indexer. In the blog they are in separate machines, but they can be in the same one. 

So in total, there's a single Wazuh Dashboard, 3 Wazuh Indexers and 2 Wazuh Server (one per cluster)

**Comment by MiguelazoDS** [comment]
Perfect!, anyway adding a dashboard on top of the architecture shouldn't cause any issue. 

Sorry for the delay, it took me some time to configure the environment without messing it up.

After the environment is working 
![Image](https://github.com/user-attachments/assets/855e0c95-a45c-4e9a-ba8f-d6bdc96fff57)
![Image](https://github.com/user-attachments/assets/cde0710d-565e-4015-bbdf-2cd500f163ac)

I stopped the indexer in cluster A
![Image](https://github.com/user-attachments/assets/d9752d08-8f66-4d2b-be81-69198d53ca2b)

And indeed it stops working as I would expect 
![Image](https://github.com/user-attachments/assets/4b2c96d6-24be-42c4-9f82-5a17f7bd0125)

The reason as far as I understand is the pattern we choose for this `*:wazuh-alerts-*` 

I tried creating separate patterns and it seems to work better 

![Image](https://github.com/user-attachments/assets/949ebb82-f42a-4fa7-a1e4-525d7eb9fc87)

Index for Cluster A still down 
![Image](https://github.com/user-attachments/assets/7ff27b6f-0026-4cb3-a15c-696c25ad2f87)

Index for Cluster B up 
![Image](https://github.com/user-attachments/assets/a141aec2-d543-493e-a00b-405e07805022)

How many clusters do you have? is it possible for you to do something like this?

**Comment by SkullKid16** [comment]
Thank you very much for your effort! I've already tried that. If I select the cluster along with the corresponding pattern and then turn it off, I can't switch to the other one either because it takes forever to load, as I think it's still searching for the one that was turned off. What I also noticed is that when I turn the cluster back on, the corresponding pattern is no longer there. I was actually planning to set up a cluster for each customer. If I then need an additional pattern for each customer and then have to change it every time I want to switch to a different cluster, it would be a bit cumbersome, but if it worked otherwise, it would be okay. Is there any way to automate this so that when the cluster is changed, it automatically selects the correct pattern?

I also noticed that when I monitor a system with the CCS environment using an agent, it is also displayed for the other clusters, as shown in the screenshot. I don't think this should be the case. Is there any way to change this?

![Image](https://github.com/user-attachments/assets/28e6481c-83b1-4153-97f2-11bdc6b9bec0)

**Comment by MiguelazoDS** [comment]
> If I select the cluster along with the corresponding pattern and then turn it off, I can't switch to the other one either because it takes forever to load, as I think it's still searching for the one that was turned off

If I understood correctly, while staying on pattern, let's say "ca*:wazuh-alerts-*", stopping the indexer on that cluster, will cause that. However for me, that worked, I could move to "cb*:wazuh-alerts-*" without any issues. Probably I didn't use my demo env too long to experience this. 

> What I also noticed is that when I turn the cluster back on, the corresponding pattern is no longer there.
> Ah, I just found out that if I update the pattern, it'll be back.

For this case, I had to reload the current page, but there was no need to recreate the index pattern. 

![Image](https://github.com/user-attachments/assets/b34c1543-f6b6-46eb-afd3-f48a504e7435)
![Image](https://github.com/user-attachments/assets/57b9facc-0f0b-449a-961b-626737cff8a3)

> I also noticed that when I monitor a system with the CCS environment using an agent, it is also displayed for the other clusters

It's strange behavior yeah, but not totally unexpected since we're breaking the architecture. But since this information comes from the API did you try adding one more entry in the  `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml` configuration file? 

![Image](https://github.com/user-attachments/assets/b63099f7-8e06-4fcd-a837-40608061818b)
![Image](https://github.com/user-attachments/assets/992455c9-7790-4a97-9c39-6d87f96104fd)

**Comment by SkullKid16** [comment]
When I select a cluster in the CCS environment and then shut it down, wait until the connection is lost, and later power it back on—while keeping it selected—the associated pattern remains intact.

The pattern only disappears if I switch to a different cluster and pattern, then power the previously shut-down cluster back on and access it again. In that case, the pattern is missing. I have to manually refresh it, and then it reappears and works as expected.

To monitor additional systems that are in the same network as the CCS environment, I added another entry in the file:
/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml

![Image](https://github.com/user-attachments/assets/d48734d2-0904-4202-9fdf-bfd215e1c5e7)

![Image](https://github.com/user-attachments/assets/4f44b646-d49e-4924-a5a9-1020509244e4)
Is there a way to configure it so that the clusters do not see these additional systems that are part of the CCS environment?

Thank you very much for your support and your time!

**Comment by MiguelazoDS** [comment]
Hi, sorry for the delay I took some days off. 

> When I select a cluster in the CCS environment and then shut it down, wait until the connection is lost, and later power it back on—while keeping it selected—the associated pattern remains intact.

Mmm that must have been my test case.

> The pattern only disappears if I switch to a different cluster and pattern, then power the previously shut-down cluster back on and access it again. In that case, the pattern is missing. I have to manually refresh it, and then it reappears and works as expected.

I'll take a look at this if there's a way to avoid refreshing it. 

>  Is there a way to configure it so that the clusters do not see these additional systems that are part of the CCS environment?

Do you mean a user from Cluster A accessing the dashboard in the CCS environment shouldn't see Cluster B and Default, which makes sense. Did I get it right? 

In that case, didn't each cluster have a dedicated dashboard to see local information? 

Anyway, I think this is what may help you with permission access https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/multi-tenancy.html 

Let me know if I got your questions right, and we'll take a deeper look at this.

**Comment by MiguelazoDS** [comment]
> However, if I install an agent on a system that's in the same network as the CCS node, the system is also displayed in clusters A and B, but as never connected.

I'll back ASAP, I need to do some tests, in the meantime I consult to the team in charge that may be faster in understanding this setup.

**Comment by MiguelazoDS** [comment]
Hi, 

I was discussing this with the indexer team, this is the environment we think you deployed.

![Image](https://github.com/user-attachments/assets/0a93b9a7-e32c-4303-9ee6-a6d7eae2ebb2)

> Now, in addition to customer clusters A and B, I also want to monitor my own systems with the CCS node. However, if I install an agent on a system that's in the same network as the CCS node, the system is also displayed in clusters A and B, but as never connected. 

This is what is really strange for us, the agents connected to a manager are retrieved by the API (the top-right tab in your dashboard), if we are using the API from A or B, there's no possibility they can retrieve an agent connected to the manager in the CCS node. 

- How did you deployed your agents in the all the nodes? 
- Are you seeing this problem in Cluster A and also Cluster B?
- Are you using a load-balancer or something that can be distributing agents between different servers? 

Regarding to the index-patterns I couldn't reproduce it, I'll keep trying that so I can provide better information to the team.

**Comment by SkullKid16** [comment]
That's exactly my setup. I installed the agents for the CCS environment as described in the instructions. I'm adding the ossec.conf of an agent to the CCS environment. I can't see the agents from cluster A in cluster B, and vice versa. It only affects the agents in the CCS environment, which are then displayed as never connected in clusters A and B. I'm not using a load balancer or anything else. I've also attached the ossec.cong of the CCS environment itself and the wazuh.yml.

Please let me know if I can provide anything else.

[ccs_env-wazuh.yml.txt](https://github.com/user-attachments/files/20666788/ccs_env-wazuh.yml.txt)

[ccs_env-agent.txt](https://github.com/user-attachments/files/20685459/ccs_env-agent.txt)

[ccs_env-ossec.conf.txt](https://github.com/user-attachments/files/20685461/ccs_env-ossec.conf.txt)

**Comment by MiguelazoDS** [comment]
Hi @SkullKid16, 

I can not download those files (only the .yml one) 

> It only affects the agents in the CCS environment, which are then displayed as never connected in clusters A and B

That's what we found really strange. I assume this was the method, as described in the blog. 

https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html

Is there a chance when you deployed the agent in the CCS environment used the wrong server IP in the UI? I installed the packages through package. 

The servers involved are not configured as clusters right? 

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html

**Comment by SkullKid16** [comment]
I've re-uploaded the files, in case you haven't seen them yet. Even when I install the packages through package, I get the same result. Clusters A and B aren't configured as clusters.

**Comment by SkullKid16** [comment]
I tried to automatically recreate the index pattern dropdown and load it with GET but it is still not displayed in the dropdown although it exists

**Comment by scrouet-neocase** [comment]
Hello,

I get an index issue with the CCS too:
![Image](https://github.com/user-attachments/assets/81b75bcf-3562-4ba5-9f3f-1e723a62638f)

The global platform has two clusters (Server+Indexer on the same VM, one VM per cluster) and the CSS server with the Dashboard and the Indexer (and an agent), everything in version 4.11.0.
Except for this error, it works fine, and I get alerts in the CCS Dashboard for both clusters.

**Comment by MiguelazoDS** [comment]
@SkullKid16, I was overwhelmed with other tasks and for this I need to recreate a CCS everytime I need to test something. I'll perform some tests between the next hours to confirm the issue. 

@scrouet-neocase Please open a thread in Slack with your problem. 

For both, we have channel in Slack for the indexer and dashboard team. I did my best here but it may be kinda slow compared to the response the team in charge can provide. 

https://wazuh.slack.com/archives/C07BZJY86G3
https://wazuh.slack.com/archives/C07CNG3M11N

**Comment by scrouet-neocase** [comment]
Hi @MiguelazoDS ,

That's what I did initially: https://wazuh.slack.com/archives/C07CNG3M11N/p1744294175728119. But @Stuti3097 asked me to post in this issue.

**Comment by MiguelazoDS** [comment]
I'll discuss that with the team later, I'll try my best @scrouet-neocase, 

I think you may be missing this step 

`Set up Cross-Cluster Search `

So you can next create the alerts pattern 

<img width="988" height="362" alt="Image" src="https://github.com/user-attachments/assets/746532e2-4890-4074-a991-c335cc433440" />

**Comment by MiguelazoDS** [comment]
@SkullKid16 I was not able to reproduce the issue, let me know if I'm understanding well 

This is the API tab 

<img width="526" height="130" alt="Image" src="https://github.com/user-attachments/assets/c5ac2b59-6efe-42c8-a3bb-1e19c4bd1278" />

Configured as you mentioned here https://github.com/wazuh/wazuh/issues/29352#issuecomment-2908060027 

Cluster A 

<img width="1915" height="594" alt="Image" src="https://github.com/user-attachments/assets/3927addd-2fa0-4e32-b227-fbc97d791667" />

<img width="724" height="255" alt="Image" src="https://github.com/user-attachments/assets/328afe87-0520-4d0b-be85-07e13c65e849" />

Cluster B 

<img width="1909" height="637" alt="Image" src="https://github.com/user-attachments/assets/56ef7b67-2f82-4938-902a-8e3453bf51a0" />

<img width="753" height="252" alt="Image" src="https://github.com/user-attachments/assets/fe3a3e7e-67e9-4521-96e9-b09147b05574" />

CCS

<img width="1902" height="582" alt="Image" src="https://github.com/user-attachments/assets/d1af5909-3810-4fbb-bd48-660f218333aa" />

<img width="716" height="194" alt="Image" src="https://github.com/user-attachments/assets/772816c4-21f8-468e-a0c5-461e175b3a5c" />

**Are you seeing in the CCS view, agents from Cluster A and Cluster B as disconnected?. Is that you issue?**

If that's the issue I don't see how can be happening, the API retrieves the agents connected to the manager. Managers are in 3 separate environments.

**Comment by scrouet-neocase** [comment]
Hi @MiguelazoDS ,

I think I've set up the Cross-Cluster search correctly:

![Image](https://github.com/user-attachments/assets/b303eeb3-66a9-453f-99a7-777df174919a)
![Image](https://github.com/user-attachments/assets/2e8eb94d-36b8-4158-8ab4-b4fed6a51eab)
![Image](https://github.com/user-attachments/assets/79b4ea70-53d0-44e0-badc-2f9c7f4bd3d3)

**Comment by MiguelazoDS** [comment]
Yeah, I think that's ok @scrouet-neocase. Are you still having issues with index patterns? 

After that, you shouldn't have issues following these steps here 

> Configure the wazuh-alerts-* index pattern 

And switching the patterns here 

<img width="526" height="136" alt="Image" src="https://github.com/user-attachments/assets/e5fc1862-53a1-4230-a87b-0da055e6effc" />

**Comment by scrouet-neocase** [comment]
Hi @MiguelazoDS ,

I still got the error when connecting today. Thus, I destroyed my 2 previous "*:wazuh-alerts-*" and created another one. I got this warning:
<img width="1174" height="294" alt="Image" src="https://github.com/user-attachments/assets/9b3fe000-6357-4b98-97e7-6bf7066a5539" />

I still get the error:
<img width="1279" height="534" alt="Image" src="https://github.com/user-attachments/assets/2fdec0bb-da17-42fe-b454-529f23ffd26c" />

**Comment by MiguelazoDS** [comment]
What do you see here? 

<img width="1275" height="708" alt="Image" src="https://github.com/user-attachments/assets/b9af5251-6dea-4b66-80a0-a0ea5461ff2f" />

**Comment by scrouet-neocase** [comment]
I see this when I want to create this index:
<img width="1675" height="478" alt="Image" src="https://github.com/user-attachments/assets/c2a91714-bf20-41c9-8c42-6991b7a4a15c" />

**Comment by scrouet-neocase** [comment]
Hello @MiguelazoDS,

Any news on my case?

Regards,

SC

**Comment by MiguelazoDS** [comment]
Hi, 

Do you have the indexes ca-wazuh-indexer.... listed in the index-pattern tab?

**Comment by scrouet-neocase** [comment]
No:
<img width="1554" height="574" alt="Image" src="https://github.com/user-attachments/assets/fe90a7e6-76d0-499c-b121-4d0ee5b676c2" />

**Comment by MiguelazoDS** [comment]
Hi, 

Did you follow this guide right? https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/

What's the logging of this command? filebeat test output

<img width="886" height="372" alt="Image" src="https://github.com/user-attachments/assets/b821ca13-e945-4b23-b15e-766096045e61" />

This is what you have 

<img width="1209" height="509" alt="Image" src="https://github.com/user-attachments/assets/2712e84f-1b47-47a6-a290-5c58aae975d1" />

I think your issue is here, what's the output of the _cat/indices endpoint for your indexer in clusters?

<img width="1116" height="169" alt="Image" src="https://github.com/user-attachments/assets/47a4a731-648e-4c65-b1e4-125856084e13" />

If the index appears there, now you must follow the instructions with the title "Set up Cross-Cluster Search" 

<img width="1411" height="459" alt="Image" src="https://github.com/user-attachments/assets/ead8d4f6-6db4-4ee5-84ab-d26ed6ee1d44" />

The index must appear here

<img width="1849" height="295" alt="Image" src="https://github.com/user-attachments/assets/74081327-c07e-4b7d-a802-64a3a631b4ce" />

If you start typing the suggested index pattern, it will show the index for your Cluster A (or whatever it is)

<img width="1211" height="577" alt="Image" src="https://github.com/user-attachments/assets/60358906-0de5-4001-9ff5-7a52259b9739" />

<img width="1352" height="285" alt="Image" src="https://github.com/user-attachments/assets/1db7eb21-f2d3-48e1-a06e-be0a357288ae" />

> [!IMPORTANT]
> If your problem is that the index is not even created in your Cluster A, please verify the following steps 

"Download the alerts template for the Wazuh indexer and grant appropriate read permissions" 
https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/

And also verify the step by step installation here 

https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#configuring-filebeat

**Comment by scrouet-neocase** [comment]
Yes, I followed this guide.
I get similar outputs on both cluster servers for filebeat, with everything 'OK'. Filebeat is not installed on the CSS server (per the guide).
But the output of the _cat/indices endpoint for my indexer in clusters is different:
<img width="1477" height="403" alt="Image" src="https://github.com/user-attachments/assets/79113de6-32b9-4ba0-bd49-ba4a13989f86" />

**Comment by MiguelazoDS** [comment]
Check the installation step by step here https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#configuring-filebeat and verify the wazuh-template is properly added 

5. Download the alerts template for the Wazuh indexer.

```
curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v4.12.0/extensions/elasticsearch/7.x/wazuh-template.json

chmod go+r /etc/filebeat/wazuh-template.json
```

6. Install the Wazuh module for Filebeat.

`curl -s https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.4.tar.gz | tar -xvz -C /usr/share/filebeat/module`

**Comment by scrouet-neocase** [comment]
I performed these steps. It worked briefly for one cluster (not the other), and I received a long list of indices with many 'red' ones.
Now I get these:
<img width="1361" height="402" alt="Image" src="https://github.com/user-attachments/assets/bab71e80-aa60-40db-89f7-d22a25e6393a" />

And I find this error in /var/log/filebeat/filebeat:
`2025-08-21T08:08:02.957Z        ERROR   [publisher_pipeline_output]     pipeline/output.go:154  Failed to connect to backoff(elasticsearch(https://10.65.1.12:9200)): Connection marked as failed because the onConnect callback failed: error loading template: could not load template. Elasticsearch returned: couldn't load template: 429 Too Many Requests: {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [1024937744/977.4mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1024857144/977.3mb], new bytes reserved: [80600/78.7kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=80600/78.7kb]","bytes_wanted":1024937744,"bytes_limit":1020054732,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [1024937744/977.4mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1024857144/977.3mb], new bytes reserved: [80600/78.7kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=80600/78.7kb]","bytes_wanted":1024937744,"bytes_limit":1020054732,"durability":"TRANSIENT"},"status":429}. Response body: {"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [1024937744/977.4mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1024857144/977.3mb], new bytes reserved: [80600/78.7kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=80600/78.7kb]","bytes_wanted":1024937744,"bytes_limit":1020054732,"durability":"TRANSIENT"}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [1024937744/977.4mb], which is larger than the limit of [1020054732/972.7mb], real usage: [1024857144/977.3mb], new bytes reserved: [80600/78.7kb], usages [request=0/0b, fielddata=0/0b, in_flight_requests=80600/78.7kb]","bytes_wanted":1024937744,"bytes_limit":1020054732,"durability":"TRANSIENT"},"status":429}. Template is: {`

**Comment by MiguelazoDS** [comment]
Filebeat is installed, is working? what's the output of the command?

**Comment by scrouet-neocase** [comment]
Except the above error that occurs every minute, filebeat works fine:
<img width="1363" height="437" alt="Image" src="https://github.com/user-attachments/assets/6041f25d-593b-4b43-a746-1ad1b1546c30" />

**Comment by MiguelazoDS** [comment]
If you can not query the indices because of that error, there are several Opensearch forums about that error, it seem a configuration issue. 

https://docs.opensearch.org/latest/install-and-configure/configuring-opensearch/circuit-breaker/
https://discuss.elastic.co/t/finding-out-cause-of-circuit-breaking-exception-data-too-large/351217
https://forum.opensearch.org/t/how-to-solve-circuit-breaker-exception-data-too-large/8153/3

I'd ask to the indexer team in the Slack channels for that specific error.

**Comment by scrouet-neocase** [comment]
Thank you @MiguelazoDS, but I don't know what to do exactly. I prefer to wait for the answer you will get from the indexer team.

**Comment by MiguelazoDS** [comment]
I was not able to reproduce, is there any configuration you're using during the deployment? you're requesting the indices from the Cluster nodes? I'll read the documentation shared before and I'll reach asap

**Comment by MiguelazoDS** [comment]
I'm back, one question, what's the configuration you have for circuit breaker? 

```console
GET /_cluster/settings?include_defaults=true
GET _nodes/stats/breaker
```

Probably you have to increase the "parent" values, but I'd like to ask to the indexer team to provide a more accurate response.

**Comment by scrouet-neocase** [comment]
The second query returns:
```
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "sanbox-wazuh-cluster",
  "nodes": {
    "DquIhO4sRO6YDYDOtJ-DAw": {
      "timestamp": 1756226331294,
      "name": "sandbox-wazuh-indexer-1",
      "transport_address": "10.65.1.12:9300",
      "host": "10.65.1.12",
      "ip": "10.65.1.12:9300",
      "roles": [
        "cluster_manager",
        "data",
        "ingest",
        "remote_cluster_client"
      ],
      "attributes": {
        "shard_indexing_pressure_enabled": "true"
      },
      "breakers": {
        "request": {
          "limit_size_in_bytes": 644245094,
          "limit_size": "614.3mb",
          "estimated_size_in_bytes": 0,
          "estimated_size": "0b",
          "overhead": 1.0,
          "tripped": 0
        },
        "fielddata": {
          "limit_size_in_bytes": 429496729,
          "limit_size": "409.5mb",
          "estimated_size_in_bytes": 0,
          "estimated_size": "0b",
          "overhead": 1.03,
          "tripped": 0
        },
        "in_flight_requests": {
          "limit_size_in_bytes": 1073741824,
          "limit_size": "1gb",
          "estimated_size_in_bytes": 0,
          "estimated_size": "0b",
          "overhead": 2.0,
          "tripped": 0
        },
        "parent": {
          "limit_size_in_bytes": 1020054732,
          "limit_size": "972.7mb",
          "estimated_size_in_bytes": 1044324656,
          "estimated_size": "995.9mb",
          "overhead": 1.0,
          "tripped": 23054
        }
      }
    }
  }
}
```

**Comment by scrouet-neocase** [comment]
The first query result is much longer (2205 lines). Do you want it all or just a party?

**Comment by MiguelazoDS** [comment]
It's ok, I consulted with the indexer team and they suggested trying the options in this file 

` /etc/wazuh-indexer/jvm.options`

The error is not reproduced in my environment, but you probably have something like this 

```
-Xms1g
-Xmx1g
```

Above there's a suggestion to use 4G, I think we can try with 2G first. 

After that change the service should be restart 

```
systemctl restart wazuh-indexer 
```

**Comment by scrouet-neocase** [comment]
I changed
```
-Xms1g
-Xmx1g
```
with
```
-Xms2g
-Xmx2g
```
and restarted the wazuh-indexer service.
The query for `/_cat/indices` works fine now and returns 156 indices. Many of them where 'red' and are 'greeen' now.

**Comment by scrouet-neocase** [comment]
Now, when I start the Dashboard:
<img width="550" height="347" alt="Image" src="https://github.com/user-attachments/assets/ee122592-3a27-4326-bf0d-de1094da10fb" />

But:
<img width="1296" height="516" alt="Image" src="https://github.com/user-attachments/assets/100f6e1c-ef76-4b50-88cd-ab68d73e74ea" />
<img width="1569" height="474" alt="Image" src="https://github.com/user-attachments/assets/0ffd5bb3-4fdf-43e8-8904-e466e834ecee" />
And:
<img width="1179" height="486" alt="Image" src="https://github.com/user-attachments/assets/a4075e54-87dc-4d9c-b420-e82a0ba169d4" />

**Comment by scrouet-neocase** [comment]
I've just reconnected to the Dashboard and got the same error:
<img width="728" height="428" alt="Image" src="https://github.com/user-attachments/assets/55c7e0b3-cbfa-4407-9935-378efe3eb02f" />
and I've lost the indices again:
<img width="1184" height="432" alt="Image" src="https://github.com/user-attachments/assets/0a56f455-1352-4e9a-9489-74aa4f6b2fe3" />

The query for `/_cat/indices` still works fine now on both clusters, with all indices 'green'.

**Comment by MiguelazoDS** [comment]
Try stopping and starting Filebeat

**Comment by scrouet-neocase** [comment]
I restarted Filebeat, and it works fine on both clusters, without any errors or warnings. But it doesn't change anything on the Dashboard.

**Comment by MiguelazoDS** [comment]
Output of this section? Set up Cross-Cluster Search https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/

**Comment by scrouet-neocase** [comment]
<img width="1342" height="521" alt="Image" src="https://github.com/user-attachments/assets/edef29fa-efa4-4ad9-b75e-6e4b0493c80e" />
<img width="1595" height="578" alt="Image" src="https://github.com/user-attachments/assets/85c6a218-ba0d-43d3-a7e3-2f174de3121d" />
<img width="1610" height="483" alt="Image" src="https://github.com/user-attachments/assets/1a79a145-ab75-4b60-bce2-ed5a6f4b7feb" />

**Comment by scrouet-neocase** [comment]
When I look for August indices on the clusters, many are missing:
<img width="848" height="96" alt="Image" src="https://github.com/user-attachments/assets/2ee170ed-d801-49e5-99cd-77b14e7df5e0" />
<img width="873" height="223" alt="Image" src="https://github.com/user-attachments/assets/cb787e41-5140-4b2f-8849-453a0555e96d" />

**Comment by MiguelazoDS** [comment]
I see that the clusters are properly connected after adding them to the cluster-remote section and testing with `_search`. Is still not possible to configure the index-pattern?

**Comment by scrouet-neocase** [comment]
It seems now possible to create the index-pattern:
<img width="671" height="615" alt="Image" src="https://github.com/user-attachments/assets/ed4b07b8-4aff-4b83-8155-baba01b4645b" />
but I have already two with the same name:
<img width="279" height="533" alt="Image" src="https://github.com/user-attachments/assets/ab512605-149d-4eb6-81aa-c9fa3da5299a" />
Should I delete them and create one again?

**Comment by MiguelazoDS** [comment]
They seem duplicate indeed, but it shouldn't affect the behavior.

**Comment by scrouet-neocase** [comment]
OK, but what should I do? Keep them and create a third one?

**Comment by MiguelazoDS** [comment]
It should be working, but I think is desirable to have just one pattern

**Comment by scrouet-neocase** [comment]
OK. I deleted the two previous "*:wazuh-alerts-*" index patterns and created a new one.
There are warnings:
<img width="1182" height="376" alt="Image" src="https://github.com/user-attachments/assets/54582eb2-b5c9-469b-813a-8c29e2515bda" />
And I still get the same error:
<img width="733" height="406" alt="Image" src="https://github.com/user-attachments/assets/5d1acf4b-a0ae-41c0-9573-c36a16f0453c" />

**Comment by MiguelazoDS** [comment]
What happened with this?

<img width="671" height="615" alt="Image" src="https://github.com/user-attachments/assets/b82e93d8-90ee-46f3-ac3f-35d66f009ba7" />

**Comment by scrouet-neocase** [comment]
It matched and still matches many indexes from both clusters, including the last ones from September.

**Comment by MiguelazoDS** [comment]
Warnings shouldn't prevent that to work, but according to the message the mapping differ in some fields. Expand the error message

**Comment by scrouet-neocase** [comment]
Here are the details:
```
INFO: Index pattern id in cookie: yes [b12c95c0-8955-11f0-89b1-030d59752763]
INFO: Getting list of valid index patterns...
INFO: Valid index patterns found: 1
INFO: Found default index pattern with title [*:wazuh-alerts-*]: yes
INFO: Checking the app default pattern exists: id [*:wazuh-alerts-*]...
INFO: Default pattern with id [*:wazuh-alerts-*] exists: no
INFO: Checking the index pattern id [b12c95c0-8955-11f0-89b1-030d59752763] exists...
INFO: Index pattern id exists [b12c95c0-8955-11f0-89b1-030d59752763]: yes
INFO: Index pattern id in cookie: yes [b12c95c0-8955-11f0-89b1-030d59752763]
INFO: Checking if the index pattern id [b12c95c0-8955-11f0-89b1-030d59752763] exists...
INFO: Index pattern id [b12c95c0-8955-11f0-89b1-030d59752763] found: yes title [*:wazuh-alerts-*]
INFO: Checking if exists a template compatible with the index pattern title [*:wazuh-alerts-*]
INFO: Template found for the selected index-pattern title [*:wazuh-alerts-*]: no
ERROR: No template found for the selected index-pattern title [*:wazuh-alerts-*]
INFO: Index pattern id in cookie: [b12c95c0-8955-11f0-89b1-030d59752763]
INFO: Getting index pattern data [b12c95c0-8955-11f0-89b1-030d59752763]...
INFO: Index pattern data found: [yes]
INFO: Refreshing index pattern fields: title [*:wazuh-alerts-*], id [b12c95c0-8955-11f0-89b1-030d59752763]...
ACTION: Refreshed index pattern fields: title [*:wazuh-alerts-*], id [b12c95c0-8955-11f0-89b1-030d59752763]
INFO: Getting settings...
INFO: Check dashboard setting [timeline:max_buckets]: 200000
INFO: App setting [timeline:max_buckets]: 200000
INFO: Settings mismatch [timeline:max_buckets]: no
INFO: Getting settings...
INFO: Check dashboard setting [metaFields]: ["_source","_index"]
INFO: App setting [metaFields]: ["_source","_index"]
INFO: Settings mismatch [metaFields]: no
INFO: Getting settings...
INFO: Check dashboard setting [timepicker:timeDefaults]: {"from":"now-24h","to":"now"}
INFO: App setting [timepicker:timeDefaults]: "{\"from\":\"now-24h\",\"to\":\"now\"}"
INFO: Settings mismatch [timepicker:timeDefaults]: no
```

**Comment by MiguelazoDS** [comment]
> INFO: Default pattern with id [*:wazuh-alerts-*] exists: no

This make me think the default index pattern is not applied. Did you configure this?

> Configure the wazuh-alerts-* index pattern

https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/

On the other hand the error 

> ERROR: No template found for the selected index-pattern title [*:wazuh-alerts-*]

Did you follow this section in the document?

> Recommendations

**Comment by scrouet-neocase** [comment]
I configured the wazuh-alerts-* index pattern:
<img width="1658" height="430" alt="Image" src="https://github.com/user-attachments/assets/8014bcba-d62f-4a1d-a499-b537b3554e1d" />
I didn't follow the last 2 recommendations. Thus:

- I've created an index retention policy, but I can't find any index related to alerts:

<img width="1147" height="417" alt="Image" src="https://github.com/user-attachments/assets/43ce7238-8410-47da-9b67-7711a027a606" />

- I've disabled the checks.template too.

**Comment by scrouet-neocase** [comment]
Indeed, with `checks.template` disabled, the error on login has disappeared.

**Comment by MiguelazoDS** [comment]
Creating the index pattern now, does not work? what's the issue?

**Comment by scrouet-neocase** [comment]
No error when I connect to the Dashboard.

The index pattern already exists:
<img width="1246" height="580" alt="Image" src="https://github.com/user-attachments/assets/7b35e542-25b4-49d0-b988-5e1204237046" />
Still with a mapping conflict:
<img width="1163" height="357" alt="Image" src="https://github.com/user-attachments/assets/06f4b482-ef17-4858-90fd-7f95ffe0b7c9" />
And no indices with the word "alert":
<img width="1124" height="412" alt="Image" src="https://github.com/user-attachments/assets/0d1fddef-de26-495b-9ca9-18294644d009" />

**Comment by MiguelazoDS** [comment]
How many cluster do you have? what happen with this? 

<img width="671" height="615" alt="Image" src="https://github.com/user-attachments/assets/0345f39f-4ad4-4292-82fb-7a083695a529" />

**Comment by scrouet-neocase** [comment]
I have two clusters for now: central and sandbox.
The screenshot you displayed was just a test to ensure there were matching indices.

**Comment by MiguelazoDS** [comment]
This is getting too long and requires more knowledge to troubleshoot this. I would insist with this https://github.com/wazuh/wazuh/issues/29352#issuecomment-3036302937 share the question in wazuh-indexer Slack channel.

Please @Stuti3097 reassign this to the proper team.

**Comment by fdalmaup** [comment]
Hi @scrouet-neocase. Thank you for your patience on this matter. 
Given that the problem you are facing is more related to Wazuh Indexer issues than Wazuh Server ones and is derived from the main problem that originated this issue, I encourage you to open an issue in the [Wazuh Indexer](https://github.com/wazuh/wazuh-indexer/issues) repository so a member of said team can assist you. Please provide them as much context as possible.
