### ISSUE TITLE
Wazuh Quickstart Script keeps getting hanged up

### ISSUE THREAD

**Issue by ArtistYay** [wazuh/wazuh#32054]
Good evening guys,

Trying to install Wazuh 4.13 on RHEL 8.10, and the 'starting Wazuh indexer installation' keeps getting hung up.

Things I've tried:

- yum update && yum cleanup all
- Turned the firewall off 'systemctl status firewalld', even with the firewall turned on, I could ping to [packages.wazuh.com](http://packages.wazuh.com/)

The first time I looked in the logs, the error had something to do with 'all mirrors were tried without success. I'll also drop the spec I've given to the VM. Any help would be appreciated.

<img width="719" height="150" alt="Image" src="https://github.com/user-attachments/assets/f34582fa-6037-43a5-b01c-e6977c1cb394" />

<img width="720" height="367" alt="Image" src="https://github.com/user-attachments/assets/66a46f2c-a6eb-4606-8beb-8dca50c77707" />

**Comment by sraaronrock** [comment]
@ArtistYay Hi! Looks like the have some issues with the repositories, more reports having issues here:
https://github.com/wazuh/wazuh/issues/32051
https://github.com/wazuh/wazuh/issues/32052

**Comment by sraaronrock** [comment]
Installation process using version 4.12.0 works. So looks like issue is related to repository. Command I used to install v.4.12.0: curl -sO https://packages.wazuh.com/4.12/wazuh-install.sh && sudo bash ./wazuh-install.sh -a

**Comment by rauldpm** [comment]
Hello! The incident should now be resolved. Please refresh your package database (apt-get update or the equivalent for your system), and then try the installation again.

**Comment by ArtistYay** [comment]
> Hello! The incident should now be resolved. Please refresh your package database (apt-get update or the equivalent for your system), and then try the installation again.

I did a dnf update and tried to install, and still got the hanging wazuh indexer install. Does it take a long time to install?

**Comment by rauldpm** [comment]
Hi @ArtistYay, please note that `dnf update` will upgrade packages. You should use `dnf makecache` instead to refresh the package manager database.

Do you still experience this problem? The installation time may vary depending on system specifications and internet speed.

**Comment by ArtistYay** [comment]
> Hi [@ArtistYay](https://github.com/ArtistYay), please note that `dnf update` will upgrade packages. You should use `dnf makecache` instead to refresh the package manager database.
> 
> Do you still experience this problem? The installation time may vary depending on system specifications and internet speed.

Yes, I used `dnf update` and `dnf makecache`, and it still gets hung up. I used the Proxmox helper script instead, and it worked.

**Comment by rauldpm** [comment]
> Yes, I used dnf update and dnf makecache, and it still gets hung up. I used the Proxmox helper script instead, and it worked.

I'm glad to hear that. Since the problem has been resolved, I'll proceed to close the issue.
