### ISSUE TITLE
CPU Maxed out after 10 minutes (ossec-analysisd possible leak)

### ISSUE THREAD

**Issue by Theoooooo** [wazuh/wazuh#4407]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.0 | analysisd | Manager | Packages | CentOS7 1908 |

I've recently upgrade all my managers and agent from 3.10.0 to 3.11.0.
I never got this issue since many version (from 3.7.2 if i remember correctly) using the same config file across all versions and upgrading processes and this is the first this happened

Since then, one of my both manager start the process ossec-analysisd and start using 100% of the CPU after a few minutes.

i got 4 cores on this VM :
![image](https://user-images.githubusercontent.com/33425208/71623618-48108e00-2bde-11ea-9195-10c3a0a23ff9.png)
10h15 : Upgrade process lanched
11h15 : Second Restart
11h45 : 1 Core used at 100%
11h50 : 2 Cores used at 100%
12h35 : 3 Cores used at 100%
13h05 : 4 Cores used at 100%

If is restart the manager being impacted by this issue, the process is started on the other manager and the same CPU usage happened with the same pattern : Using 1 core, then 2, 3, and 4, maxing out the CPU of the VM.

If you need any specific informations let me know because it could be a serious issue

**Comment by Zenidd** [comment]
Hello @Theoooooo,

Thanks for your detailed issue description, we really appreciate it. I think this issue is probably related to https://github.com/wazuh/wazuh/issues/4400.

 Seems like in Wazuh v3.11, `ossec-analysisd` isn't correctly handling some windows events, maybe due to the new Eventchannel [events format](https://github.com/wazuh/wazuh/pull/3320) related to Eventchannel events format. In your graph, It's visible how threads are blocked one by one as they receive an event that blocks them indefinitely. 




Stay tuned to track the fixing process. We will also write any workaround we find or anything that can help on https://github.com/wazuh/wazuh/issues/4400

Best regards and thanks again,
JP Sáez

**Comment by Theoooooo** [comment]
@Zenidd Even disabling <check_sys> didn't mitigate the issue. My manager still caps out his CPU usage :/
There must be another type of event that trigger this issue

**Comment by Theoooooo** [comment]
@Zenidd Even with disabling root_check section, i still got issue with this thread blocking issue !
Any way to debug this out ? It's a major issue and it should be fixed quickly to prevent users creating tons of issue

**Comment by vikman90** [comment]
Hi @Theoooooo,

This problem is not related to Rootcheck but to the component in Analysisd that decodes logs coming from Windows Eventchannel.

Hot fix: reduce the number of Windows Eventchannel decoder threads to 1:

```shell
echo 'analysisd.winevt_threads=1' >> /var/ossec/etc/local_internal_options.conf
service wazuh-manager restart
```

We're working on a fix right now and will publish it as soon as possible.

Apologies for the inconveniences.
Kind regards.

**Comment by Theoooooo** [comment]
@vikman90 
Thank you for the hot fix.
Did the upcoming fix will change that value back to default ? Or did i need to keep a reminder somewhere to change that value back to normal after the upcoming fix ?

**Comment by Theoooooo** [comment]
@vikman90 
This quick solution does not fix an important issue with the manager : While there is only one thread affected to the windows Event, it simply locks up every windows event incoming into the manager, leading to a huge loss of event because they cannot be treated in time.

Check this graph as the count get really low as the thread get locks up :
![image](https://user-images.githubusercontent.com/33425208/71674488-9dce6d00-2d7b-11ea-9033-d1a4cbd316bc.png)

**Comment by vikman90** [comment]
Hi @Theoooooo,

Yes, this bug affects the Windows Eventchannel decoder, that's why I suggested you reduce the number of threads to 1. However, the decoder still fails.

We've fixed this issue (#4412) for 3.11.1, that will be released as soon as possible.

Thank you for your well-detailed explanation, and sorry again for the inconvenience.

Let me close this issue.
Best regards.
