### ISSUE TITLE
Removal of the ossec-init.conf file from the Wazuh installations - Exploratory

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7090]
### Description 

As part of the epic https://github.com/wazuh/wazuh/issues/7054, we have the main goal of removing the `/etc/ossec-init.conf` file from the Wazuh installations.

This change affects mani use cases like installations, upgrades, uninstallations, utilities, etc. So, after finalizing the implementation of the epic, exploratory testing should be done in order to make sure that everything is working as expected.

**Comment by DProvinciani** [comment]
We found some `wazuh-control` executions used to obtain the version information that used the parameters in a bad way. This was fixed in the next pull request.

https://github.com/wazuh/wazuh-packages/pull/610.

**Comment by palaciosjeremias** [comment]
We found some issues during the installation/upgrade process 
- An error during a merge that generates the installation to continue even after the user selects to not update Wazuh.
- A bad usage of **wazuh-control** when finding Wazuh installed type that unchains an error on building steps.
- A wrong comparison that unchains a bad service usage to stop Wazuh

**Comment by palaciosjeremias** [comment]
An improvement for robustness was found:
Wazuh installation process should only consider Wazuh as installed if the control binary is found on the installation path in case other binaries like the service files were left during an uninstallation

**Comment by palaciosjeremias** [comment]
Finding:
The upgrade using packages on Ubuntu doesn't eliminate obsolete files outside of the installation path **/var/ossec**. It does with all obsolete files inside the folder.

**Comment by pereyra-m** [comment]
It was found that some files were still present after a package uninstallation.
The issue #7253 describes this situation.

**Comment by pereyra-m** [comment]
After the following tests in CentOS 7 for Manager/Agent, no issues were found:
- Upgrade with packages/sources (from `v4.0.4`)
- Clean install with packages/sources

It was confirmed that:
- The log has no errors
- The `ossec-init.conf` file and its symbolic link are not present
- The `wazuh-control` tool prints the correct information

**Comment by DProvinciani** [comment]
During the packages review, we found a bad usage of the `sed` command in the AIX installer. This platform does not support the `-i` switch so, we removed the switch from all the installers to make it work in AIX, and also for having some consistency between all the installers.

https://github.com/wazuh/wazuh-packages/pull/613

**Comment by pereyra-m** [comment]
Some other scenarios were tested, for Manager/Agent with sources/packages in CentOS 7:

#### Simulating a new v4.2.1 release

An upgrade was performed from the current 4.2.0 develop version to a fake one. 
This upgrade didn't involved the `ossec-init.conf` file because it was no more present after this implementation. All the information was provided by the binary `wazuh-control`.

No issues were found.

#### Incomplete uninstallation 

Some files were left in a system with no Wazuh binaries installed: `ossec-init.conf` and some backup configuration files in `/var/ossec/etc`.
The installation script was able to determine there wasn't a previous installation present, with the enhancement mentioned in this [comment](https://github.com/wazuh/wazuh/issues/7090#issuecomment-765034618).

No issues were found.
